---
title: "Code for BLUP analysis"
output: 
  html_document:
    toc: FALSE
---





# Getting started

You will be able to find on this site the code as well as the comments relating to this code which are associated with the article :
<br />
**PREDICTING ALZHEIMER'S CONVERSION USING GENETIC AND GREY-MATTER RISK SCORES**

# Abstract

Alzheimer's disease (AD) polygenic risk scores (PRS) have recently gained in prediction accuracy, though they remain limited to the genetic component of the disorder (heritability). To overcome this limitation, we constructed grey-matter risk scores (GMRS) of familial history of AD that may capture environmental or genetic AD risk untagged by the current PRS. Together, PRS and GMRS boosted the prediction of AD conversion (and of AD biomarkers), with both scores contributing to the prediction. Identifying individuals at risk of converting could help clinicians to target interventions or researchers to identify prodromal markers of the disease.

